[project]
name = "snippets-test"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "argon2-cffi>=23.1.0",
    "psqlpy>=0.9.0",
    "sanic>=24.12.0",
    "uvicorn>=0.34.0",
]
