[project]
name = "snippets-test"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "casu",
    "muffin>=0.102.3",
    "uvicorn>=0.34.0",
]

[tool.uv.sources]
casu = { path = "../casu", editable = true }
